'use client'

import { useRef, useState } from 'react'
import { FileCheck2, FilePlus2, Trash2, Upload } from 'lucide-react'

type LocalDocument = { id: string; name: string; size: string }

export function DocumentsManager() {
  const input = useRef<HTMLInputElement>(null)
  const [documents, setDocuments] = useState<LocalDocument[]>([])

  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-gold-deep">Document organizer</p><h1 className="mt-1 font-display text-4xl font-bold">My documents</h1><p className="mt-3 text-muted">Keep a local working list of the documents your move may require.</p></div><button type="button" onClick={() => input.current?.click()} className="gold-button"><Upload size={17} />Add documents</button><input ref={input} type="file" multiple className="hidden" onChange={(event) => { const added = Array.from(event.target.files ?? []).map((file) => ({ id: `${file.name}-${file.lastModified}`, name: file.name, size: `${Math.max(1, Math.round(file.size / 1024))} KB` })); setDocuments((current) => [...current.filter((item) => !added.some((newItem) => newItem.id === item.id)), ...added]); event.target.value = '' }} /></div><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_.4fr]"><section className="card-surface p-6"><h2 className="text-xl font-extrabold">Uploaded this session</h2>{documents.length ? <div className="mt-5 space-y-3">{documents.map((document) => <div key={document.id} className="flex items-center gap-4 rounded-xl border border-line p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-gold-soft"><FileCheck2 size={19} /></span><div className="min-w-0 flex-1"><p className="truncate font-bold">{document.name}</p><p className="text-xs text-muted">{document.size}</p></div><button type="button" onClick={() => setDocuments((current) => current.filter((item) => item.id !== document.id))} aria-label={`Remove ${document.name}`} className="grid size-10 place-items-center rounded-xl text-danger hover:bg-danger/10"><Trash2 size={18} /></button></div>)}</div> : <button type="button" onClick={() => input.current?.click()} className="mt-5 grid min-h-56 w-full place-items-center rounded-card border-2 border-dashed border-line bg-canvas text-center"><span><FilePlus2 className="mx-auto text-gold-deep" /><strong className="mt-3 block">Add your first document</strong><small className="mt-1 block text-muted">PDFs and images can be selected from your device.</small></span></button>}</section><aside className="card-surface h-fit p-6"><h2 className="font-extrabold">Privacy note</h2><p className="mt-3 text-sm leading-6 text-muted">This first version displays selected filenames only for the current browser session. Files are not uploaded to Nexit or Neon.</p></aside></div></div>
}
