'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import type { RelocationProfile } from '@/lib/profile'

export function SettingsForm({ initial, email }: { initial: RelocationProfile; email: string }) {
  const [profile, setProfile] = useState(initial)
  const [updates, setUpdates] = useState(true)
  const [message, setMessage] = useState('')
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage('Saving…'); const response = await fetch('/api/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: profile.display_name, current_country: profile.current_country, timeline: profile.timeline, priority: profile.priority }) }); setMessage(response.ok ? 'Settings saved.' : 'Unable to save settings.') }
  return <div className="mx-auto max-w-3xl"><div><p className="text-sm font-bold text-gold-deep">Account</p><h1 className="mt-1 font-display text-4xl font-bold">Settings</h1></div><form onSubmit={save} className="card-surface mt-7 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-extrabold">Your Nexit Profile</h2><p className="mt-1 text-sm text-muted">Status: {profile.wizard_status === 'completed' ? 'Complete' : 'Not Started'}</p></div><Link href="/profile-wizard" className="rounded-xl border border-navy px-4 py-2 text-sm font-bold">{profile.wizard_status === 'completed' ? 'Edit Profile / Retake Wizard' : 'Start Wizard'}</Link></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Display name<input className="field mt-2" value={profile.display_name ?? ''} onChange={(event) => setProfile({ ...profile, display_name: event.target.value || null })} /></label><label className="text-sm font-bold">Email<input className="field mt-2 bg-canvas" value={email} disabled /></label><label className="text-sm font-bold">Current country<input className="field mt-2" value={profile.current_country ?? ''} onChange={(event) => setProfile({ ...profile, current_country: event.target.value || null })} /></label><label className="text-sm font-bold">Move timeline<select className="field mt-2" value={profile.timeline ?? ''} onChange={(event) => setProfile({ ...profile, timeline: (event.target.value || null) as RelocationProfile['timeline'] })}><option value="">Not selected</option><option>0-3 months</option><option>3-6 months</option><option>6-12 months</option><option>12+ months</option><option>Just researching</option></select></label></div><label className="mt-7 flex items-center justify-between gap-4 rounded-xl bg-canvas p-4"><span><strong className="block text-sm">Planning reminders</strong><small className="text-muted">Show helpful progress notifications in Nexit.</small></span><input type="checkbox" checked={updates} onChange={(event) => setUpdates(event.target.checked)} className="size-5 accent-gold" /></label><div className="mt-7 flex items-center gap-4"><button className="gold-button">Save changes</button><span role="status" className="text-sm text-muted">{message}</span></div></form></div>
}
